name: Kambiz Ghost Streamer

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */5 * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo (Force Latest)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0 
          clean: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install FFmpeg (The Engine)
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Force NPM to STOP Being a Bitch
        run: |
          npm init -y
          npm pkg set overrides.libsodium-wrappers="0.7.10"
          npm install discord.js-selfbot-v13 @dank074/discord-video-stream sqlite3 tweetnacl

      - name: Run The Encrypted Ghost Bot
        env:
          TOKEN: ${{ secrets.TOKEN }}
          KAMBIZ_ID: ${{ secrets.KAMBIZ_ID }}
        run: node index.js
